config/routes.rb
Rails.application.routes.draw do


  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'} 
	root "sensors#index"
	get '/about', to: 'pages#about', as: 'about'
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :sensors, except: [:index]
  get 'my-sensors', to: 'sensors#index', as: 'user_sensors'
  get 'sensor/:id', to: 'sensors#show', as: 'sensor_show'

  resources :users, except: [:new, :edit, :destroy]
  get 'my-account', to: 'users#show', as: 'user_account'
  get 'add-sensor', to: 'sensors#new', as: 'add_sensor'
  
  resources :locations, except: [:index]
  get 'location/:id', to: 'locations#show', as: 'location_show'
  get 'add-location', to: 'locations#new', as: 'add_location'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord

validates :name, presence: true
has_many :sensors
belongs_to :user

extend FriendlyId
friendly_id :name, use: :slugged

end

app/models/sensor.rb
class Sensor < ApplicationRecord
	validates :name, presence: true
	validates :nameduino, presence: true
	belongs_to :user
	belongs_to :location

	extend FriendlyId
    friendly_id :name, use: :slugged

    after_create :remake_slug

  # Try building a slug based on the following fields in
  # increasing order of specificity.
  def slug_candidates
    [
      :name,
      [:name, :id],
    ]
  end

  def remake_slug
    self.update_attribute(:slug, nil)
    self.save!
  end

  #You don't necessarily need this bit, but I have it in there anyways
  def should_generate_new_friendly_id?
    new_record? || self.slug.nil?
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	validates :name, presence: true
	has_many :sensors
	has_many :locations

	after_create :init_profile

	def init_profile
    	Location.create(name: "none", user_id: User.last.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
  include DefaultPageContent
end

app/controllers/concerns/default_page_content.rb
module DefaultPageContent
	extend ActiveSupport::Concern

	included do 
		before_action :set_title
	end

	def set_title
  	@page_title = "Inspectuino"
    end
end

app/controllers/concerns/devise_whitelist.rb
 module DeviseWhitelist
 	extend ActiveSupport::Concern
	included do
		before_action :configure_permitted_parameters, if: :devise_controller?
	end

	def configure_permitted_parameters
	  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :IP])
	  	devise_parameter_sanitizer.permit(:account_update, keys: [:name, :IP])
	end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

before_action :restriction, only: [:index, :new, :create, :show]
before_action :set_location, only: [:show, :edit, :update]

    def index

	    $list = @user.locations

	end

	def new
		@location = Location.new
	end
 
	def create

		@location = Location.new(location_params)
		@location.user = current_user
		
		if @location.save
			redirect_to add_sensor_path
		else
			render 'new'
		end	
	end   


	def edit
   	
		if @location.user == current_user
		else
		   redirect_to root_path
	    end

	end

	def update
        
		#@location.user = current_user
		if @location.update(location_params)
			redirect_to location_path(@location)
		else
			render 'edit'
		end

	end 

	def show

        if @location.user == current_user
		else
		redirect_to new_location_path 
		end
		@page_title = @location.name
	end
	

	private

	def location_params
		params.require(:location).permit(:name, :description)
	end


	def restriction

		if user_signed_in? 
		@user = current_user
		else
         #redirect_to :controller => 'users', :action => 'new'
         redirect_to new_user_session_path  
      	end


	end

	def set_location
	@location = Location.friendly.find(params[:id])
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home

	end
 
	def about

	end   

end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController

before_action :restriction, only: [:index, :new, :create, :show, :edit, :update]
before_action :set_sensor, only: [:show, :edit, :update]
before_action :check_site_res, only: [:index, :show]
before_action :set_data, only: [:index, :show]
before_action :check_data_format, only: [:index, :show]

    def index

	    $list = @user.sensors

	end

	def new
			@sensor = Sensor.new
	end
 
	def create

		@sensor = Sensor.new(sensor_params)
		@sensor.user = current_user
		
		if @sensor.save
			redirect_to user_sensors_path
		else
			render 'new'
		end	
	end   


	def edit

		if @sensor.user == current_user
		else
		   redirect_to root_path
	    end

	end

	def update
        
		#@sensor.user = current_user
		if @sensor.update(sensor_params)
			redirect_to sensor_path(@sensor)
		else
			render 'edit'
		end

	end 

	def show

        if @sensor.user == current_user
		else
		redirect_to new_sensor_path 
		end
		@page_title = @sensor.name
	end
	

	private

	def sensor_params
		params.require(:sensor).permit(:name, :nameduino, :description, :location_id, :low, :high, :divisor, :unit)
	end

	def set_data

	if @code.to_i == 200 or @code.to_i == 302
		        data = Nokogiri::HTML(open(@user.IP))
				$data2 = data.text.split(" ")
			else 
				redirect_to edit_user_registration_path 
			end
	end


	def check_site_res

		 	begin
		     
		    res = Net::HTTP.get_response(URI(@user.IP))
		     
		    rescue 
		      @code=res.code
		    else
		      @code=res.code

		    ensure

		    return @code
		   
		    end
 
	end

	def restriction

		if user_signed_in? 
		@user = current_user
		else
         #redirect_to :controller => 'users', :action => 'new'
         redirect_to new_user_session_path  
      	end


	end


	def check_data_format 
    
	end

	def set_sensor
	@sensor = Sensor.friendly.find(params[:id])
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

#layout "user"
before_action :restriction, only: [:show]
  

	def show
		@user = current_user


		 	begin
		     
		    res = Net::HTTP.get_response(URI(@user.IP))
		     
		    rescue 
		      @code=res.code
		    else
		      @code=res.code

		    ensure

		    return @code
		   
		    end
 

 
	end

	def restriction

		if user_signed_in? 

		else
        	redirect_to new_user_session_path   
      	end

	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def login_helper style

		if current_user
	  	   (link_to "Logout", destroy_user_session_path, method: :delete, class: style)+ " ".html_safe +
	       (link_to "My Account", user_account_path, class: style)+ " ".html_safe +
	       (link_to "Edit My Account", edit_user_registration_path, class: style)
		else
			(link_to "Login", new_user_session_path, class: style)+ " ".html_safe +
			(link_to "Register", new_user_registration_path, class: style)
		end
	end

	def restriction_helper style
		if current_user
	       (link_to "My Sensors", user_sensors_path, class: style)+'<li class="nav-item">'.html_safe +
	       (link_to "Add Sensor", add_sensor_path, class: style)+'<li class="nav-item">'.html_safe +
	       (link_to "Add Location", add_location_path, class: style)
		end
	end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="card text-dark bg-warning border-danger mb-3">
      <div class="card-body">
        <div id="error_explanation">
          <h2>#{sentence}</h2>
          <ul>#{messages}</ul>
        </div>
      </div>
    </div>
    HTML


    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/views/layouts/_navigation.html.erb
    <div class="container">

      <header class="masthead">
        <h3 class="text-muted"><%= @page_title %></h3>

        <nav class="navbar navbar-expand-md navbar-light bg-light rounded mb-3">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav text-md-center nav-justified w-100">
               <li class="nav-item">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/about">About</a>
              </li>
              <li class="nav-item">
               <%= restriction_helper 'nav-link' %>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01"
                 data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                 Account</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                  <%= login_helper 'dropdown-item' %>
                </div>
              </li>
            </ul>
          </div>
        </nav>
      </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

<%= render 'layouts/navigation' %>

<!-- <%= render "shared/nav"%> 
   <p class="notice"><%= notice %></p> 
  <p class="alert"><%= alert %></p>  -->




    <%= yield %>
</body>
 <!-- <footer class="footer text-center">
      <p>&copy; Copyright 2017 Marek Owsianowski</p>
  </footer> -->

  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'users', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= login_helper %>

  	<p class="notice"><%= notice %></p>
  	<p class="alert"><%= alert %></p>


    <%= yield %>

  </body>
</html>

app/views/locations/edit.html.erb
<div class="card border-info w-50 mx-auto bg-white">

	<div class="card-body">
			<h5 class="card-title text-dark text-center">Edit location</h5>


<% if @location.errors.any? %>
<h2>The following errors prevented the location from being saved</h2>
<ul>
<% @location.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= simple_form_for @location do |f| %>

 	<div class="form-inputs">
 		<%= f.label :name %>
 		<%= f.text_field :name, class: 'form-control' %>
 	</div>

	<div class="form-inputs">
 		<%= f.label :description %>
 		<%= f.text_field :description, class: 'form-control' %>
 	</div>
 	<br>
 	<div class="actions">
 		<%= f.submit "Save", class: 'btn btn-primary btn-block'%>
 	</div>
<% end %>
</div>
</div>

app/views/locations/new.html.erb
<div class="card border-info w-50 mx-auto bg-white">

	<div class="card-body">
			<h5 class="card-title text-dark text-center">Create new location</h5>


<% if @location.errors.any? %>
<h2>The following errors prevented the location from being saved</h2>
<ul>
<% @location.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= simple_form_for @location do |f| %>

 	<div class="form-inputs">
 		<%= f.label :name %>
 		<%= f.text_field :name, class: 'form-control' %>
 	</div>

	<div class="form-inputs">
 		<%= f.label :description %>
 		<%= f.text_field :description, class: 'form-control' %>
 	</div>
 	<br>
 	<div class="actions">
 		<%= f.submit "Create", class: 'btn btn-primary btn-block'%>
 	</div>
<% end %>
</div>
</div>

app/views/locations/show.html.erb
dsadsa

<h1>location name = <%= @location.name %> </h1>  <br>
<h1>location desc = <%= @location.description %> </h1>  <br>
<%= link_to "edit", edit_location_path(@location) %>

<%= @location.name %> 

app/views/pages/about.html.erb
<h1>Inspect your signals with that website</h1>
<p class="lead">Take your Arduino with some web shield and share outputs of your sensors. Download this <a class="link" href="https://bitbucket.org/marekows/inspectuino/src/master/ArduinoWebServer">Code</a> for your Arduino. Open port on your router for your Arduino. Then you can share output of your sensors to Inspectuino. Now you can managed of your outputs.
If you haven't Arduino and you only want to check how Inspectuino works, use link for this site (https://inspectuino.herokuapp.com/about). Check below, there are fake outputs, start manage them with Inspectuino.</p>

<h7>A0 324
A1 319
A2 327
A3 310
A4 291
A5 283
D0 1
D1 1
D2 0
D3 0
D4 0
D5 1
D6 0
D7 1
D8 0
D9 0 </h7>

app/views/pages/home.html.erb
sadsa

app/views/sensors/_list.html.erb
	
    <% $nr += 1 %>
	<% nm = list.nameduino %>
	<% if list.divisor.to_i == 0 %>
	<% divisor = 1 %>
	<% else %>
	<% divisor = list.divisor.to_i %>
	<% end %>

	<% if $data2.index(nm).nil? %>
   
	<tr class="table">
    <tr class="table-warning">
      <th scope="row"><%= list.name %></th>
      <td>Where</td>
		<th scope="row">Can't find sensor with nameduino <%= nm %> on your server.</th>
	<td><%= link_to "Edit", edit_sensor_path(list.friendly_id), :class=>"btn btn-info", :role=>"button"%></td>
    </tr>


	<% else %>

	<% index_nm = $data2.index(nm) %>
	
	<% $data2[index_nm + 1] %> 
	<% result = $data2[index_nm + 1] %>


	<tr class="table">

      <th scope="row"><%= list.name %></th>

      	<% a = Location.find (list.location_id) %> 
 		<td><%= a.name %> </td>

      <% if result.to_i == 1 %>
			<td><%= list.high %></td>
	  <% elsif result.to_i == 0 %>
			<td> <%= list.low %></td>
	  <% else %>
	  		<td><%= result.to_i/divisor %><%= list.unit %></td>
	  <% end %>
	<td><%= link_to "Show", sensor_show_path(list.friendly_id), :class=>"btn btn-info", :role=>"button"%></td>
    </tr>
   <% end %>

app/views/sensors/_list_ruler.html.erb
<hr>

app/views/sensors/_listtest.html.erb
    	<div class="col-md-8">
	<% $nr += 1 %>
	

	<% nm = list.nameduino %>
	<% index_nm = $data2.index(nm) %>
	<% $data2[index_nm + 1] %>  

          
            <%= list.name %>
			<% result = $data2[index_nm + 1] %>

			<% if result.to_i == 1 %>
			ON 
			<% else %>
			OFF 
			<% end %>
			
			<% $arrayAllSensors << list.nameduino  %> 
            
            

<%= link_to "details", sensor_show_path(list.friendly_id), :class=>"btn btn-primary", :role=>"button"%>

</div>

app/views/sensors/_table_list.html.erb
<table class="table table-striped table-bordered table-hover">
   <thead class="thead-light">
    <tr>
      <th scope="col">Sensor</th>
      <th scope="col">Location</th>
      <th scope="col">State</th>
      <th scope="col">Details</th>
    </tr>
  </thead>
 <tbody>

<% $nr = 0 %>
<% $value = 1 %>
<% $arrayAllSensors = [] %> 

<%= render partial: 'list', collection: $list %>

</tbody>
</table>

app/views/sensors/edit.html.erb
<div class="card border-info w-65 mx-auto bg-white">

	<div class="card-body">
			<h5 class="card-title text-dark text-center">Edit sensor</h5>

<% if @sensor.errors.any? %>
<h2>The following errors prevented the todo from being saved</h2>
<ul>
<% @sensor.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= simple_form_for @sensor do |f| %>

 	<div class="form-inputs">
 		<%= f.label :name %>
 		<%= f.text_field :name, class: 'form-control' %>
 	</div>
 	<br>
	<div class="form-inputs">
 		<%= f.label :nameduino, required: true %>
 		<em>(It's connection pin, like "A3" - analog Pin 3 or "D6" - digital Pin 6)</em>
 		<%= f.text_field :nameduino, class: 'form-control' %>
 	</div>
 	<br>
	<div class="form-inputs">
 		<%= f.label :description %>
 		<%= f.text_area :description, class: 'form-control' %>
 	</div>
	<br>
	<div class="form-inputs">
		 <%= f.label "Choose location of sensor" %>
 		 <%= f.select :location_id,  @user.locations.all.collect {|c| [ c.name, c.id ] }, class: 'form-control slct-box'%>
 	</div>

 	<br>
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Representation of digital signal</h5>
	<div class="form-inputs">
	<%= f.label "When signal HIGH (logical 1), state:" %>
 <%= f.select :high,  options_for_select(["HIGH", "ON", "OFF", "OK", "DANGER", "OPEN", "CLOSED", "ONLINE", "OFFLINE"], @sensor.high), class: 'form-control slct-box'%>
 	</div>

	<div class="form-inputs">
	<%= f.label "When signal LOW (logical 0), state:" %>
 	<%= f.select :low,  options_for_select(["LOW", "ON", "OFF", "OK", "DANGER", "OPEN", "CLOSED", "ONLINE", "OFFLINE"], @sensor.low), class: 'form-control slct-box'%>
 	</div>
 	    </div>
    </div>
  </div>

    <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Representation of analog signal</h5>
	<div class="form-inputs">
 		<%= f.label :divisor, 'Devide analog signal by:' %>
 		<em>(type 10, to devide signal by 10)</em>
 		<%= f.text_field :divisor, class: 'form-control' %>
 	</div>
<br>
 	 	<div class="form-inputs">
	<%= f.label "Choose unit of analog signal" %>
 	<%= f.select :unit,  options_for_select(["", "°F", "°C"," inch", " cm", " m", " kg"," g"], @sensor.unit), class: 'form-control slct-box'%>
 	</div>
      </div>
    </div>
  </div>
</div>


 <div class="actions">
 		<%= f.submit "Save", class: 'btn btn-primary btn-block'%>
 	</div>
<% end %>
</div>
</div>

app/views/sensors/index.html.erb
<% if @user.sensors.count == 0 %>
<%= render partial: 'shared/welcome' %>
<% else %>
<%= render partial: 'table_list' %>
<% end %>

app/views/sensors/new.html.erb
<div class="card border-info w-65 mx-auto bg-white">

	<div class="card-body">
			<h5 class="card-title text-dark text-center">Create new sensor</h5>

<% if @sensor.errors.any? %>
<h2>The following errors prevented the sensor from being saved (Nameduino is Connection Pin)</h2>
<ul>
<% @sensor.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= simple_form_for @sensor do |f| %>

 	<div class="form-inputs">
 		<%= f.label :name %>
 		<%= f.text_field :name, class: 'form-control' %>
 	</div>
 	<br>
	<div class="form-inputs">
 		<%= f.label :nameduino, required: true %>
 		<em>(It's connection pin, like "A3" - analog Pin 3 or "D6" - digital Pin 6)</em>
 		<%= f.text_field :nameduino, class: 'form-control' %>
 	</div>
 	<br>
	<div class="form-inputs">
 		<%= f.label :description %>
 		<%= f.text_area :description, class: 'form-control' %>
 	</div>
	<br>
	<div class="form-inputs">
		 <%= f.label "Choose location of sensor" %>
 		 <%= f.select :location_id,  @user.locations.all.collect {|c| [ c.name, c.id ] }, class: 'form-control slct-box'%>
 </div>
 	<br>
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Representation of digital signal</h5>
	<div class="form-inputs">
	<%= f.label "When signal HIGH (logical 1), state:" %>
 	<%= f.select :high,  options_for_select(["HIGH", "ON", "OFF", "OK", "DANGER", "OPEN", "CLOSED", "ONLINE", "OFFLINE"]), class: 'form-control slct-box'%>
 	</div>

 	<div class="form-inputs">
	<%= f.label "When signal LOW (logical 0), state:" %>
 	<%= f.select :low,  options_for_select(["LOW", "ON", "OFF", "OK", "DANGER", "OPEN", "CLOSED", "ONLINE", "OFFLINE"]), class: 'form-control slct-box'%>
 	</div>

      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Representation of analog signal</h5>
	<div class="form-inputs">
 		<%= f.label :divisor, 'Devide analog signal by:' %>
 		<em>(type 10, to devide signal by 10)</em>
 		<%= f.text_field :divisor, class: 'form-control' %>
 	</div>
<br>
 	 	<div class="form-inputs">
	<%= f.label "Choose unit of analog signal" %>
 	<%= f.select :unit,  options_for_select(["", "°F", "°C"," inch", " cm", " m", " kg"," g"]), class: 'form-control slct-box'%>
 	</div>
      </div>
    </div>
  </div>
</div>

 	<br>
 	<div class="actions">
 		<%= f.submit "Create", class: 'btn btn-primary btn-block'%>
 	</div>
<% end %>
</div>
</div>

app/views/sensors/show.html.erb
<% index_nm = $data2.index(@sensor.nameduino) %>

<% result = $data2[index_nm + 1] %>
<% divisor = @sensor.divisor.to_i %>
<div class="card border-info w-50 mx-auto bg-light text-center">
	

	    	<div class="card-body">
	    		<h5 class="card-title text-dark">Sensors details</h5>	    	

<table class="table table-striped table-bordered table-hover table-fit">
 <tbody>
    <tr>
      <th scope="col">Name</th>
      <td scope="row"><%= @sensor.name %></td>
      </tr>
      <th scope="col">Connection Pin</th>
      <td scope="row"><%= @sensor.nameduino %></td>
      </tr>
      <th scope="col">Location</th>
      <td scope="row"><%= @sensor.location.name%></td>
    </tr>
   <th scope="col">Read Value</th>
   <td scope="row"><%= result = $data2[index_nm + 1] %></td>
    </tr>

<% if result.to_i > 1 %>
   

    <th scope="col">Divisor of analog signal</th>
   <td scope="row"><%= @sensor.divisor %></td>
    </tr>

    <th scope="col">Unit of measurement</th>
   <td scope="row"><%= @sensor.unit %></td>
    </tr>

   <th scope="col">Calculate Value</th>
   <td scope="row"><%= result.to_i/divisor %><%= @sensor.unit %> </td>
  </tr>

<% else %>


   <th scope="col">State when value "1" </th>
   <td scope="row"><%= @sensor.high %></td>
    </tr>
   <th scope="col">State when value "0" </th>
   <td scope="row"><%= @sensor.low %></td>
    </tr>

<% end %>

    <th scope="col">Created on </th>
 	<td scope="row"><%= @sensor.created_at.strftime("%Y-%m-%d")%></td>
 	</tr>

 	<th scope="col">Updated on </th>
 	<td scope="row"><%= @sensor.updated_at.strftime("%Y-%m-%d")%></td>
 	</tr>

 </tbody>
</table>
	<div class="card bg-light ">
	<div class="card-body">
      <h5 class="card-title text-dark">Description</h5>
      <p class="card-text"><%= @sensor.description %></p>
    </div>
    </div>

<%= link_to "Edit", edit_sensor_path(@sensor), :class => 'btn btn-primary btn-block' %>

app/views/shared/_firstlogin.html.erb
<div class="jumbotron">
          <h1>Enter IP address of your board!</h1>
          <p class="lead">You need to open your singals to the world. Just connect your board with router and open port on it. 
		  If you want to quickly check how site works, you can use this address (fake Arduino signals):  https://inspectuino.herokuapp.com/about <br>
          You need to have specyfic arduino program for data output</p>
          <!-- <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p> -->
</div>

app/views/shared/_nav.html.erb
<% if current_user %>
  	  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <%= link_to "My Sensors", user_sensors_path %> <br>
      <%= link_to "My Account", user_account_path %> <br>
      <%= link_to "Edit My Account", edit_user_registration_path %>
      <%= link_to "Add Sensor", add_sensor_path %> <br>
	<% else %>
		<%= link_to "Login", new_user_session_path %>
		<%= link_to "Register", new_user_registration_path %>
<% end %>

app/views/shared/_notification.html.erb
<% if notice or alert %>  
    <div class="card text-dark bg-warning border-danger mb-3">
    	<div class="card-body">
		<p class="notice"><%= notice %></p> 
		<p class="alert"><%= alert %></p>
		</div>
	</div>
<% end %>  

app/views/shared/_welcome.html.erb
 <!-- Jumbotron -->
<div class="jumbotron">
          <h1>Let's Inspect your signals!</h1>
          <p class="lead">For first add some location, where you put yours sensors. Like Kitchen, Bathroom and any other room, place etc. For next add some sensors, like light sensor, motion sensor and any other possible, it's all about you. </p>
          <!-- <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p> -->
</div>

app/views/users/show.html.erb
<div class="card border-info w-50 mx-auto bg-light text-center">
	    	

	    	<div class="card-body">
	    		<h5 class="card-title text-dark"><%= @user.name %>, this is your account details</h5>
	    		<div class="card border-info bg-light">
	    		<div class="card-body">
	    		<p class="card-text">You have <%= @user.sensors.count %> sensors, on pins: </p>
	    		
	    		<% list = @user.sensors %> 
	    		
	    		<% list.each do |list| %>  

				<%= link_to list.nameduino, sensor_show_path(list.id), :class=>"badge badge-success" %> 

				<% end %><br>
				</div>
				</div>
				</br>
	    		<div class="card border-info bg-light ">
	    		<div class="card-body">
				<p class="card-text">You have <%= @user.locations.count - 1 %> locations: </p>

				<% list = @user.locations %> 
				<% list.each do |list| %> 
				<% if list.name != "none" %> 
				<%= link_to list.name, location_show_path(list.id), :class=>"badge badge-success" %> 
				<% end %>
				<% end %>
</div>
</div>
</br>
<div class="card border-info bg-light">

<div class="card-body">

	<div class="alert alert-success" role="alert">
 	<p class="card-text">Your account was create on <%= @user.created_at.strftime("%Y-%m-%d") %></p>
</div>

		

<div class="alert alert-success" role="alert">
  <p class="card-text">Last updated of your account details was on <%= @user.updated_at.strftime("%Y-%m-%d") %></p>
  </div>
</div>
</div>
	</div>
</div>